services:
  - type: web
    name: odoo-hospital-system
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        fromDatabase:
          name: odoo-db
          property: host
      - key: USER
        fromDatabase:
          name: odoo-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: odoo-db
          property: password
      - key: PORT
        value: "5432"

databases:
  - name: odoo-db
    plan: free
    databaseName: odoo
    user: odoo
